### ISSUE TITLE
Invalid Examples for Sending transactions using Cis2Contract class.

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-node-sdk-js#176]
**Bug Description**
As the usages are highlighted here 
https://github.com/Concordium/concordium-node-sdk-js/blob/main/packages/web/example/SendCIS2Transfer.html
https://github.com/Concordium/concordium-node-sdk-js/blob/main/packages/web/example/SendCIS2UpdateOperator.html

The schema returned from `contract.createUpdateOperator({energy: 10000n}, update)`. Cannot be used directly with `walletApi.sendTransaction(connectedAccount, type, payload, json, schema)` since the types are different. `createUpdateOperator` method returns a parameter schema.

**Steps to Reproduce**
execute the example

**Expected Result**
The schema returned from `createUpdateOperator` should be directly be usable with ``walletApi.sendTransaction`.

**Actual Result**
build error

**Versions**
- Software Version
@concordium/web-sdk: 3.5.0

- OS
- Browser
- Mobile device, if applicable

**Comment by parv0888** [comment]
Hi @soerenbf 
Apologies that my comment might be confusing. I was only referring to the types being used. Hope the screenshot will clarify a bit. 
I get this typescript error when i try to use the code as it is
![image](https://user-images.githubusercontent.com/1246947/236186068-db0ef34f-2eed-4256-87de-7a7ee32bd0e8.png)

It requires a cast. So the following code works fine
![image](https://user-images.githubusercontent.com/1246947/236186271-8e20a3b4-fa9d-4c66-9e25-47574405aba0.png)

Just wanted to point this out as the first version (with error) is the version which is available in the examples.

**Comment by soerenbf** [comment]
This will be fixed by making the browser wallet API compatible with the schema format returned by `CIS2Contract.createUpdateOperator` and `CIS2Contract.createTransfer` in upcoming patch version 2.5.1 of `@concordium/browser-wallet-api-helpers` instead of in this repository.

Here is a link to the PR https://github.com/Concordium/concordium-browser-wallet/pull/308

Closing this issue.
