### ISSUE TITLE
Support for CIS0.`supports` function `CIS2Contract` class

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-node-sdk-js#177]
**Description**
As explained by [CIS2 Standard](https://proposals.concordium.software/CIS/cis-2.html) CIS2 standard should also following CIS0. Which has the function [`supports`](https://proposals.concordium.software/CIS/cis-0.html#supports). However there is not support for the same function in [Cis2Contract](https://github.com/Concordium/concordium-node-sdk-js/blob/main/packages/common/src/cis2/CIS2Contract.ts) class
https://github.com/Concordium/concordium-node-sdk-js/blob/main/packages/common/src/cis2/CIS2Contract.ts

**Steps to Reproduce**
NA

**Expected Result**
functions of CIS0 should also be supported.

**Actual Result**
NA

**Versions**
- Software Version
@concordium/web-sdk: 3.5.0

- OS
- Browser
- Mobile device, if applicable

**Comment by soerenbf** [comment]
Hi @parv0888. This is already available, however currently it is imported as it's own function. 

```
import { cis0Supports } from '@concordium/web-sdk';
```

**Comment by parv0888** [comment]
thanks
