### ISSUE TITLE
`Try .. catch` block is missing in `deserializeTypeValue` function which causes the errors not to be thrown correctly

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-node-sdk-js#196]
**Bug Description**

`Try .. catch` block is missing in `deserializeTypeValue` function which causes the errors not to be thrown correctly.
https://github.com/Concordium/concordium-node-sdk-js/blob/main/packages/common/src/deserialization.ts#L321

See the `Try .. catch` blocks in the above functions on how errors are thrown.

**Steps to Reproduce**

Running the [front-end] (https://github.com/Concordium/concordium-misc-tools/pull/55) and choosing the `wrong_schema` option at one of the two `dropDowns` at the front end then pressing the button in that test unit should cause an error. When comparing these two errors:
 
When comparing the errors returned by the functions `deserializeReceiveReturnValue()` and `deserializeTypeValue()`:

The error from `deserializeTypeValue()` can not be cast correctly. `(err as string)` is used in the below line to overcome this issue:
https://github.com/Concordium/concordium-misc-tools/blob/171c7a82549db58f1db5d53b21ec1a7805754315/wallet-connect-test-bench/src/Transactions.tsx#L170

The error from `deserializeReceiveReturnValue()` can be cast correctly. `(err as Error).message` is used in the below line:
https://github.com/Concordium/concordium-misc-tools/blob/171c7a82549db58f1db5d53b21ec1a7805754315/wallet-connect-test-bench/src/Transactions.tsx#L158 (edited)

**Comment by shjortConcordium** [comment]
`deserializeTypeValue` is not supposed to have a try catch block, because the error from rust should already be properly formatted. (_That_ might be bugged though)
