### ISSUE TITLE
Module '"@concordium/node-sdk"' has no exported member 'parseWallet'

### ISSUE THREAD

**Issue by arslanpixpel** [Concordium/concordium-node-sdk-js#204]
**can't use parse wallet to get signer and sender**

**install package and import parsWallet**

**parse wallet should work**

**parseWallet not found**

**Comment by soerenbf** [comment]
Hi @arslanpixpel 

Can you provide a little more detail? For example:

- Which version of the SDK are you using?
- In which environment (nodejs/web)
- Typescript or javascript?
- Maybe a screenshot of the error in your editor?

Thanks!

**Comment by arslanpixpel** [comment]
Hi @soerenbf,  version is 7.0.0

**Comment by soerenbf** [comment]
So while the `parseWallet` function is available on the `main` branch of the repository, it doesn't look like it has been included in a release yet.

The only thing the function does is invoke `JSON.parse` on a string and validate the format. If you don't care about validating the format, I'd suggest you just use `JSON.parse` for now.

Out of curiosity, what pointed you in the direction of using this function?
