### ISSUE TITLE
Support the changes of the GRPCv2 API for the new protocol

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node-sdk-js#207]
**Task description**

The SDK should have its GRPC dependency upgraded in order to support the changes that has been made to the GRPC API for the new consensus protocol.

An overview of the changes can be found here:
https://github.com/Concordium/concordium-node/issues/870
https://github.com/Concordium/concordium-node/issues/871

**Comment by soerenbf** [comment]
When this is done, this needs to cascade to concordium-browser-wallet as well for it to be used with the new consensus version.
