### ISSUE TITLE
Publish generated documentation

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-node-sdk-js#209]
Check this comment for details:

https://github.com/Concordium/concordium-node-sdk-js/pull/198#issuecomment-1600402699

Also go through the documentation make sure there are no references to the url used when testing (rasmus-kirk.github.io/...)

**Comment by abizjak** [comment]
Can you also please add the link to the generated documentation to the about section of the repository
![Screenshot from 2023-06-21 13-13-31](https://github.com/Concordium/concordium-node-sdk-js/assets/105212/61c20163-bb8f-43c1-972a-e35f1bd5e9ee)
