### ISSUE TITLE
Conversion helpers between `CCD` and `microCCD`

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-node-sdk-js#214]
**Task description**

It would be helpful to have a function `toCCD(microCCDAmount)` and `toMicroCCD(CCDAmount)` to convert between `CCD` and `microCCD` similar to `fromWei`/`toWei` functions:
https://github.com/web3/web3.js/blob/4.x/packages/web3-utils/src/converters.ts#L467

**Comment by shjortConcordium** [comment]
Note that we have the following for the browser wallet, which contains something like these features:
https://github.com/Concordium/concordium-wallet-common-helpers/blob/main/src/utils/ccd.ts
(So maybe they just need to be ported/adjusted

**Comment by DOBEN** [comment]
yes, exactly I am looking for the `microCcdToCcd` function if it is exported by a package already so it is available at the front end via the webSDK.

**Comment by shjortConcordium** [comment]
I just meant that, for the one fixing this issue, that they don't need to create the methods from scratch. That "package" is not one we actually release/expose.

**Comment by bisgardo** [comment]
The piggybank dapp has [this](https://github.com/Concordium/concordium-dapp-piggybank/blob/main/src/amount.ts):
```
export function microCcdToCcdString(amount: bigint) {
    const int = amount / BigInt(1e6);
    const frac = amount % BigInt(1e6);
    return `${int}.${frac.toString().padStart(6, '0')}`;
}
```
