### ISSUE TITLE
Add `toJSON` and `toString` methods on newtype classes (`sdk/src/types/*`)

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-node-sdk-js#308]
**Task description**
The purpose of adding the functionality above is to:

- Make it easier to use the types in string interpolation (by adding `toString`)
- Standardise how the types are represented in a JSON compatible manner (by adding `toJSON`), i.e.
  - types wrapping single values are unwrapped (e.g. `AccountAddress` and `Timestamp`)
  - types wrapping multiple values are represented as objects including just those values (e.g. `ContractAddress`)
  - bigints should still be represented as bigints, and should be left up to dependants to use something like [`json-bigint`](https://www.npmjs.com/package/json-bigint) or a custom replacer function to tailor how bigints are serialised for their particular use-case.

_IMPORTANT_:
This would not normally be considered a breaking change, but until a browser wallet version with the changes proposed in #307 are implemented and utilised in a released version of the browser wallet, it will be due to the browser wallet currently relying on `instanceof` checks included in [`transformConcordiumType`](https://github.com/Concordium/concordium-node-sdk-js/blob/1c859a070351507f9cbb6ccd06952e95b8711f7c/packages/sdk/src/types/json.ts#L91).

**Comment by abizjak** [comment]
I don't think `toString` and `toJSON` should be the same. For example, we use the `<index, subindex>` format when representing account addresses, but that is not how we do it in JSON.

If you want to name things differently that's fine, but there should be a way to render the account address as `<index, subindex>` string.

**Comment by soerenbf** [comment]
> I don't think `toString` and `toJSON` should be the same. For example, we use the `<index, subindex>` format when representing account addresses, but that is not how we do it in JSON.
> 
> If you want to name things differently that's fine, but there should be a way to render the account address as `<index, subindex>` string.

Adding this for reference, since this has already been discussed:

The purpose of the task is to add
- `toString` method to more easily use the types in contexts that calls `toString` method on types given (e.g. in [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
- `toJSON` method to unwrap newtype patterns to their inner values (e.g. `Energy {value: bigint}` = `bigint`, and `ContractAddress {index: bigint, subindex: bigint}` = `{index: bigint, subindex: bigint}`). The latter example might not seem relevant, but the default `toJSON` of classes also includes private fields in the object returned which we cannot have.

**Comment by lassemoldrup** [comment]
@abizjak @soerenbf 

1. It seems like all of the modules already have `toUnwrappedJSON` functions. Should these be removed?
2. Where can I find a reference for the "canonical" string representations?

**Comment by soerenbf** [comment]
> @abizjak @soerenbf
> 
> 1. It seems like all of the modules already have `toUnwrappedJSON` functions. Should these be removed?
> 2. Where can I find a reference for the "canonical" string representations?

1. That would be a breaking change. I think for now we should just mark it as `@deprecated - use <Type>.toJSON instead`. The end goal is, that the whole `sdk/src/types/json.ts` module is removed, so if you could deprecate all of that in the same go, that would be awesome 😄 
2. Let's discuss when you have time in office.

**Comment by limemloh** [comment]
> - bigints should still be represented as bigints, and should be left up to dependants to use something like [json-bigint](https://www.npmjs.com/package/json-bigint) or a custom replacer function to tailor how bigints are serialised for their particular use-case.

Why don't we represent bigints are something which is supported by JSON? like strings?
We have some cases like the schema, where it needs to be a certain format of JSON, but that is covered by other functions, so I don't see why we define a JSON format for the user, but leave the interpretation of bigint up to them.

**Comment by soerenbf** [comment]
> @soerenbf
> 
> > * bigints should still be represented as bigints, and should be left up to dependants to use something like [json-bigint](https://www.npmjs.com/package/json-bigint) or a custom replacer function to tailor how bigints are serialised for their particular use-case.
> 
> Why don't we represent bigints are something which is supported by JSON? like strings? We have some cases like the schema, where it needs to be a certain format of JSON, but that is covered by other functions, so I don't see why we define a JSON format for the user, but leave the part of formatting bigint up to them.

We can probably all agree that javascript is the odd one out in terms representing integers, and I think it would be weird to have the types serialize differently than how it is done in our other SDK's as that would make them incompatible. At least when looking at the rust SDK, all `u64` wrappers are represented as `number`s in JSON, with the exception of `Amount`. I don't know if the rest of our SDK's all follow this format as well?

As an example, our mobile wallets deserialize transaction payloads received through wallet connect. In our own apps, the serialization of the payloads is done by utilizing the JS SDK, and the expected format is that bigint wrapper types are represented as numbers in JSON, with the exception of `CcdAmount`.

**Comment by limemloh** [comment]
We don't have a standardize JSON format for our types, but we could choose to let the Rust SDK dictate it.

My main objection is that we put a `toJSON` method on all of our types which does not actually produce JSON without the user having to deal with the decision on how to serialize bigints.
If we want to comply to the Rust SDK JSON format, they will need to make the right decision for the bigint.

If we want to use bigint, then I don't think it should be done as a `toJSON` method, but rather a separate function like we already have.
The issue related to the default `toJSON` leaking the private fields could be solved by defining `toJSON` throw an error.

**Comment by lassemoldrup** [comment]
After some discussion, we have decided that will not create `toJSON` methods for types that use `bigint`, since both solutions could cause confusion.
