### ISSUE TITLE
Isolate NodeJS dependent code 

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-node-sdk-js#33]
**Task description**
Currently the SDK is not usable outside of nodeJS environments, because the node client uses nodeJS specific libraries, and is everything is exported from the index.

We should restructure the SDK, so that modules reliant on nodeJS is isolated, and the SDK can easily be used in web environments.

**Comment by orhoj** [comment]
Closed as a duplicate of https://github.com/Concordium/concordium-node-sdk-js/issues/30.
