### ISSUE TITLE
Publish packages from CI

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-node-sdk-js#349]
**Task description**
It would be nice to have the process of releasing new versions of the SDK and dependency packages automated through CI.

Can have a look at the deploy flows in https://github.com/Concordium/concordium-dapp-libraries/blob/main/.github/workflows/build%2Brelease.yml

**Comment by rasmus-kirk** [comment]
We should probably stop using the GH-actions maintained by Michael if possible.
