### ISSUE TITLE
Add support for configure delegation transaction

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-node-sdk-js#36]
**Task description**

For protocol 4, the configure delegation transaction type is added. We should have support for serializing/sending it.

**Comment by abizjak** [comment]
What is the status of this @shjortConcordium ? Has it already been done?

**Comment by shjortConcordium** [comment]
Yes, I implemented it, because I needed it for testing. I assigned myself so no one would start implementing it again.

**Comment by abizjak** [comment]
Can you please move the task to "Done" then? Thanks.
