### ISSUE TITLE
Fix intToString

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-node-sdk-js#54]
**Bug Description**

`util.js`'s `intToString` doesn't work (as in it doesn't do anything)
This function is used to parse uint64 types from the node.
The impact of this is that we don't convert number fields into string before letting JS parse it, which means that we have incorrect/lossy parsing of numbers above MAX_SAFE_INTEGER.

**Comment by abizjak** [comment]
Please provide details.

Is this something that needs to be urgently addressed? What is the impact?

**Comment by shjortConcordium** [comment]
Updated description. It will potentially cause a lot of weird errors in the future, but as far as I know we don't really have any values that exceed MAX_SAFE_INTEGER yet.
(I expect to release the fix for this next week)
