### ISSUE TITLE
Explain how to get signing keys

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-node-sdk-js#58]
**Description**
Currently, the process of getting your signing keys is not properly explained.
This task is about delineating the process so that it is easy to get started using the SDK.

As I understand it, there are at least the two following ways:

1. Import and decrypt the mobile wallet export with `decryptMobileWalletExport`, then find the signing keys inside the (partially typed) record.
2. Import and decrypt the mobile wallet export with `decryptMobileWalletExport`, then use the `IdentityInput` to create a new account to which you generate the keys.

**Comment by orhoj** [comment]
@Bargsteen I don't think this is something that is documented for any of the SDK's, and it is really independent of the chosen SDK as for all of them you have to get access to your private keys somehow. Also, I am not sure if we want to focus on people using mobile wallet exports for this as it is something we are about to remove for the future mobile wallet.

**Comment by Bargsteen** [comment]
@orhoj Okay. I created the issue after realising that some users ran into this exact problem.

This might not be an issue if it becomes significantly easier to get your private keys with the browser wallet. But otherwise, we should document the process somewhere. The fact that the other SDKs don't include this information, does not mean that information is not valuable 😊

**Comment by orhoj** [comment]
@Bargsteen My point was only that the description should be generic as I assume that users of any of our SDKs would run into the same issue.

**Comment by Bargsteen** [comment]
Ok 👍 , I'll close this for now, then 😊
