### ISSUE TITLE
Links on NPM package is broken

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-node-sdk-js#77]
**Description**
Links on NPM package is broken

**Steps to Reproduce**
Visit https://www.npmjs.com/package/@concordium/node-sdk
click on "[Note that this package contains and exports the functions from the common-sdk, check the readme of that package for an overview of those](https://github.com/Concordium/concordium-node-sdk-js/blob/common/README.md)."

**Expected Result**
It should redirect to a readme file

**Actual Result**
it shows a 404 not found page.

**Comment by shjortConcordium** [comment]
This has been fixed in the latest releases. Thank you.
