### ISSUE TITLE
Add parsing of contract return values.

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-node-sdk-js#86]
**Description**

Currently the SDK does not offer a way to deserialize/parse the return value from a contract execution. It could be useful to have such a function.

**Comment by rasmus-kirk** [comment]
I'm working on this, almost done with the receive functions and I am working on adding init functions. It's modeled as two separate functions `deserialize_return_value_receive` and  `deserialize_return_value_init` because the init functions does not have a function name in the schemas.
